### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by SruthiVeerepall**
[#16 ](https://github.com/WSUCEG-7140/Team-Yellove/issues/16)

*)The task involves developing an API endpoint for user registration in the restaurant management project. This endpoint will allow external clients, such as front-end applications or other services, to interact with the system and register new users. The registration process should follow a standardized API design and include necessary validations for data integrity and security.

### CODE REVIEW

**Comment by tejaswini-minupala** [comment]
It looks good and it implementing proper  authentication and authorization mechanisms  for the user registration in the restaurant management project.

**Comment by PravalikaPalakolu** [comment]
Authentication is working fine and i am able to register.

**Comment by ashishchidurala** [comment]
I am able to implement the authentication code. The mechanism is also working fine.

**Comment by SruthiVeerepall** [comment]
ASE 1

**Pull request merged**
