### PR TITLE
Testcases

### PR DESCRIPTION
**Pull request by SruthiVeerepall**
[Issue #30 ](https://github.com/WSUCEG-7140/Team-Yellove/issues/30)

The behaviour of APIs. This can be done manually using a tool like Postman and automated using Django.

In this activity, we will perform manual API testing using Postman. This involves sending requests to APIs and verifying the responses. We will also automate unit tests using Django. This involves writing Python code that tests the functionality of our APIs.

### CODE REVIEW

**Comment by manibabuveerepalli** [comment]
There are totally 15 testcases. And they are all working fine.

**Comment by SruthiVeerepall** [comment]
test


Test cases are working fine.

**Comment by PravalikaPalakolu** [comment]
Yes, all test cases are working fine.

**Comment by ashishchidurala** [comment]
15 test cases are working.

**Pull request merged**
