### PR TITLE
Menus

### PR DESCRIPTION
**Pull request by SruthiVeerepall**
[#13](https://github.com/WSUCEG-7140/Team-Yellove/issues/13)
*) Created API endpoints to menu items like(Name, Category, Price)
*)Added Item category filter feature 

[#11](https://github.com/WSUCEG-7140/Team-Yellove/issues/11)
*)The creation of various API endpoints is currently underway. These include the implementation of functionalities such as viewing the menu, placing the order, tracking the order status.

### CODE REVIEW

**Comment by manibabuveerepalli** [comment]
Yes, It is good. We are able to retrieve the menu items based on the category and based on the items.
And we added the APIs like order tracking and status of the order

**Comment by PravalikaPalakolu** [comment]
Code is fine. I am able to retrieve the ṃenu items.

**Comment by ashishchidurala** [comment]
I am able to get the menu items based on the category. and also code is looking fine for me.

**Comment by tejaswini-minupala** [comment]
the code is fine. I am able to get the menu items based on the category also.

**Comment by SruthiVeerepall** [comment]
ASE3

**Comment by SruthiVeerepall** [comment]
These are the list of menu items

**Pull request merged**
