### PR TITLE
Added Tracking Status Feature

### PR DESCRIPTION
**Pull request by SruthiVeerepall**
[#14 ](https://github.com/WSUCEG-7140/Team-Yellove/issues/14)
*)Designing Data Models in Django
*)Implementing Views
*)Setting Up Routes
*)Conducting API Testing

### CODE REVIEW

**Comment by manibabuveerepalli** [comment]
The code is fine. I am able to track the order status

**Comment by PravalikaPalakolu** [comment]
Its working fine. I am able to f wet tch the status of the order.

**Comment by ashishchidurala** [comment]
I am bale to track the order status. But may be should work on the updating the status on its own.

**Comment by tejaswini-minupala** [comment]
Yes Ashish, We will work on the updating the order status by its own on upcoming sprints, when we create the login and registration of user. By then we can able to do that.

**Comment by PravalikaPalakolu** [comment]
ASE6

I am able to track the status of the order

**Pull request merged**
