### PR TITLE
Orders

### PR DESCRIPTION
**Pull request by SruthiVeerepall**
[Issue #21](https://github.com/WSUCEG-7140/Team-Yellove/issues/21)

*) Implement API endpoints for placing an order in the restaurant management project. These endpoints will allow clients to create and submit orders for food or beverages, facilitating seamless transactions and order processing.

### CODE REVIEW

**Comment by PravalikaPalakolu** [comment]
Here, the code correctly implements creating a new order, its storage and handling the tasks associated with it. I see it working good.

**Comment by manibabuveerepalli** [comment]
The code is fine, which is implementing the creating a new order.

**Comment by tejaswini-minupala** [comment]
The code looks cool and Implement API endpoints for placing an order in the restaurant management project.

**Comment by SruthiVeerepall** [comment]
ASE7



This is for creating the orders.

**Pull request merged**
