### PR TITLE
Implemented search functionality for the item list based on the name …

### PR DESCRIPTION
**Pull request by tejaswini-minupala**
[Issue #22 ](https://github.com/WSUCEG-7140/Team-Yellove/issues/22)

*) The task involves implementing search functionality for menu items in the restaurant management project's API. This feature enables clients to search for specific food or beverage items based on keywords or filters, allowing for a more convenient and efficient menu browsing experience.

### CODE REVIEW

**Comment by SruthiVeerepall** [comment]
Code is looking fine. I am able to search the items in the menu.

**Comment by PravalikaPalakolu** [comment]
I am able to search for the items in the menu items. So the filter is working fine.

**Comment by ashishchidurala** [comment]
Code is fine, i am able to use the filter.

**Comment by manibabuveerepalli** [comment]
I am able to retrieve the items from the search.

**Comment by tejaswini-minupala** [comment]
ASE5

**Pull request merged**
